[package]
name = "out"
version = "3.1.0"
authors = ["evenorog <evenorog@gmail.com>"]
description = "Provides functionality to get the n largest items from slices and iterators."
documentation = "https://docs.rs/out"
repository = "https://github.com/evenorog/out"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["min", "max", "sort", "iterator"]
categories = ["algorithms", "no-std"]
exclude = ["/.travis.yml"]
edition = "2018"

[features]
default = ["alloc"]
alloc = []

[badges]
travis-ci = { repository = "evenorog/out" }
maintenance = { status = "actively-developed" }

[dev-dependencies]
rand = { version = "0.7.0", features = ["small_rng"]}
quickcheck = "0.8.5"
quickcheck_macros = "0.8.0"
